### ISSUE TITLE
When selecting multiple paragraphs, you cannot emphasize multiple paragraphs when using list numbers or ordinal numbers

### ISSUE THREAD

**Issue by wisepmlin** [stevengharris/MarkupEditor#4] opened 2021-12-21 10:16 UTC
When selecting multiple paragraphs, you cannot emphasize multiple paragraphs when using list numbers or ordinal numbers

**Comment by stevengharris** [comment] 2021-12-21 18:22
Thanks, will take a look when I am back to cleanup some of the loose ends, soon I hope. The problem is in markup.js in _toggleFormat. It needs to be smarter in general about how to deal with ranges that span elements.

**Comment by wisepmlin** [comment] 2021-12-21 18:24
It's nice to see the open source editor you offer. I have been running the kit normally, but I am testing the stability of the software. I found that when I clicked New Page, sometimes I couldn't get the focus in the input box, and I needed to try to click multiple times.
The second point: I am trying to add ordinals to the edited text, I can only add sequence symbols one by one in a paragraph way, I can't select multiple paragraphs, and add sequences to multiple paragraphs at once.





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Steve ***@***.***&gt;; 
发送时间: 2021年12月22日(星期三) 凌晨2:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [stevengharris/MarkupEditor] When selecting multiple paragraphs, you cannot emphasize multiple paragraphs when using list numbers or ordinal numbers (Issue #4)





 
Thanks, will take a look when I am back to cleanup some of the loose ends, soon I hope. The problem is in markup.js in _toggleFormat. It needs to be smarter in general about how to deal with ranges that span elements.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wisepmlin** [comment] 2021-12-21 18:46
I found that TheOlbarTextField often gets the focus for the first time to work, but after multiple times the Focus Is not working, I can't get the focus at this time, click on the input box, I rear action




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "stevengharris/MarkupEditor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月22日(星期三) 凌晨2:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [stevengharris/MarkupEditor] When selecting multiple paragraphs, you cannot emphasize multiple paragraphs when using list numbers or ordinal numbers (Issue #4)





 
Thanks, will take a look when I am back to cleanup some of the loose ends, soon I hope. The problem is in markup.js in _toggleFormat. It needs to be smarter in general about how to deal with ranges that span elements.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wisepmlin** [comment] 2021-12-22 13:27
In the toolkit, images are added via url, and the addition often fails, and there is no UI update after saving in the view

**Comment by stevengharris** [comment] 2022-06-08 23:30
Multiselection operations are fixed on main and should be fully supported as of 0.3.3.

**Closed by stevengharris** 2022-06-08 23:30 UTC
